#!/usr/bin/env node
// bitbaum.github.io/hire — the "Live work" list, derived from the fleet register.
//
// WHY THIS EXISTS
//
// The list used to be hand-typed HTML, and on 2026-09-12 it carried four
// defects at once, on the page that matters most commercially:
//
//   - it linked https://revampit.orangecat.ch, a host RETIRED on 2026-09-10.
//     It answers 200 because it is a permanent redirect, so nothing looked
//     broken and nothing reported it.
//   - it listed RevampIT *and* evig as two separate pieces of live work. They
//     are the same system: the organisation renamed. One system, counted twice,
//     to a prospect counting systems.
//   - it named the clinic "VitaReBa", a name retired in favour of "Vita".
//   - it named the housing product "AOZ Wohnen", which is neither its current
//     name (AOZ Begleitung) nor the retired one on record.
//
// None of those broke anything. That is exactly the problem, and it is why
// bitbaum/fleet's AGENTS.md says: a page that types the portfolio is a copy —
// generate it, or do not ship it. This is the generator.
//
// The register (FleetCrown's public API, joined from apps.conf + project
// profiles) owns WHERE each system currently lives. work.json owns grouping,
// display name and the sentence. Neither owns the other's half.
//
//   node build.mjs            fetch register, rewrite index.html, save snapshot
//   node build.mjs --offline  build from register.snapshot.json
//   node build.mjs --check    exit 1 if index.html is not what the register produces

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const REGISTER_URL = process.env.FLEET_REGISTER_URL ?? "https://fleetcrown.orangecat.ch/api/fleet/register";
const SNAPSHOT = join(here, "register.snapshot.json");
const INDEX = join(here, "index.html");
const START = "<!-- WORK:START — generated by build.mjs; do not edit by hand -->";
const END = "<!-- WORK:END -->";

const args = new Set(process.argv.slice(2));

async function loadRegister() {
  if (!args.has("--offline")) {
    try {
      const res = await fetch(REGISTER_URL, { signal: AbortSignal.timeout(8000) });
      if (res.ok) {
        const json = await res.json();
        writeFileSync(SNAPSHOT, JSON.stringify(json, null, 2) + "\n");
        return json;
      }
      console.error(`register answered ${res.status}; using snapshot`);
    } catch (e) {
      console.error(`register unreachable (${e?.message ?? e}); using snapshot`);
    }
  }
  if (!existsSync(SNAPSHOT)) throw new Error("no register and no snapshot — cannot build");
  return JSON.parse(readFileSync(SNAPSHOT, "utf8"));
}

const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/"/g, "&quot;");

/**
 * Resolve each editorial entry against the register.
 *
 * A slug with no register row and no `extras` URL is a BUILD FAILURE, not a
 * skipped row. Silently dropping it would turn the retirement of a product
 * into its quiet disappearance from the page — and the failure mode this
 * generator exists to fix was precisely a stale entry nobody noticed.
 */
export function resolveWork(register, cfg) {
  const bySlug = new Map(register.rows.map((r) => [r.slug, r]));
  const items = [];
  const problems = [];

  for (const [slug, o] of Object.entries(cfg.work)) {
    const row = bySlug.get(slug);
    const extra = cfg.extras?.[slug];
    const url = extra?.url ?? row?.site?.url ?? null;
    if (!url) {
      problems.push(`${slug}: no register row with a URL, and no extras entry`);
      continue;
    }
    if (!cfg.groups.some((g) => g.id === o.group)) {
      problems.push(`${slug}: unknown group "${o.group}"`);
      continue;
    }
    items.push({ slug, name: o.name, what: o.what, url, group: o.group, order: o.order ?? 99 });
  }
  return { items, problems };
}

/** One system must not appear twice, whatever it is called. */
export function findDuplicateHosts(items) {
  const byHost = new Map();
  for (const it of items) {
    const host = it.url.replace(/^https?:\/\//, "").replace(/\/.*$/, "").toLowerCase();
    if (!byHost.has(host)) byHost.set(host, []);
    byHost.get(host).push(it.name);
  }
  return [...byHost.entries()].filter(([, names]) => names.length > 1);
}

export function renderWork(items, cfg) {
  const out = [];
  for (const g of cfg.groups) {
    const rows = items.filter((i) => i.group === g.id).sort((a, b) => a.order - b.order || a.name.localeCompare(b.name));
    if (!rows.length) continue;
    out.push(`    <div class="group">`);
    out.push(`      <p class="group-label">${g.label}</p>`);
    out.push(`      <ul class="work">`);
    for (const r of rows) {
      out.push(`        <li><a href="${esc(r.url)}">${esc(r.name)}</a>`);
      out.push(`          <span>${esc(r.what)}</span></li>`);
    }
    out.push(`      </ul>`);
    out.push(`    </div>`);
  }
  return out.join("\n");
}

export function splice(html, block) {
  const a = html.indexOf(START);
  const b = html.indexOf(END);
  if (a === -1 || b === -1 || b < a) {
    throw new Error("index.html is missing the WORK:START / WORK:END markers");
  }
  return html.slice(0, a + START.length) + "\n" + block + "\n" + html.slice(b);
}

const register = await loadRegister();
const cfg = JSON.parse(readFileSync(join(here, "work.json"), "utf8"));
const { items, problems } = resolveWork(register, cfg);

if (problems.length) {
  console.error("work.json does not agree with the register:");
  for (const p of problems) console.error(`  - ${p}`);
  process.exit(1);
}

const dupes = findDuplicateHosts(items);
if (dupes.length) {
  console.error("the same host is listed under more than one name:");
  for (const [host, names] of dupes) console.error(`  - ${host}: ${names.join(", ")}`);
  console.error("One system counted twice overstates the work. Drop one.");
  process.exit(1);
}

const html = readFileSync(INDEX, "utf8");
const next = splice(html, renderWork(items, cfg));

if (args.has("--check")) {
  if (html !== next) {
    console.error("index.html differs from the register — run: node build.mjs");
    process.exit(1);
  }
  console.log(`index.html is in sync with the register (${items.length} systems)`);
} else {
  writeFileSync(INDEX, next);
  console.log(`wrote index.html (${items.length} systems, register ${register.generatedAt ?? "snapshot"})`);
}
